// Mock useLanguage hook for demonstration

export const translations = {
  en: {
    shop: 'Book Shop',
    searchBooks: 'Search books...',
    addToCart: 'Add to Cart',
    orderNow: 'Order Now',
    price: 'Price',
    inStock: 'In Stock',
    outOfStock: 'Out of Stock',
    quantity: 'Quantity',
    filter: 'Filter',
    allCategories: 'All Categories',
    cart: 'Cart',
    total: 'Total',
    checkout: 'Checkout',
    orderSuccess: 'Order placed successfully!',
    pages: 'pages',
    published: 'Published',
    category: 'Category',
    author: 'Author',
    rating: 'Rating',
    reviews: 'reviews',
    addedToCart: 'Added to cart!',
    cartEmpty: 'Your cart is empty',
    continueReading: 'Continue your reading journey',
    featuredBooks: 'Featured Books',
    newArrivals: 'New Arrivals',
    bestsellers: 'Bestsellers',
    viewDetails: 'View Details',
    quickView: 'Quick View',
    wishlist: 'Add to Wishlist',
    removeFromCart: 'Remove from cart',
    proceedToCheckout: 'Proceed to Checkout',
    backToShopping: 'Back to Shopping',
    orderTotal: 'Order Total',
    subtotal: 'Subtotal',
    shipping: 'Shipping',
    free: 'Free'
  },
  sw: {
    shop: 'Duka la Vitabu',
    searchBooks: 'Tafuta vitabu...',
    addToCart: 'Ongeza kwenye Mkoba',
    orderNow: 'Agiza Sasa',
    price: 'Bei',
    inStock: 'Ipo Dukani',
    outOfStock: 'Haipatikani',
    quantity: 'Idadi',
    filter: 'Chuja',
    allCategories: 'Makundi Yote',
    cart: 'Mkoba',
    total: 'Jumla',
    checkout: 'Maliza Ununuzi',
    orderSuccess: 'Agizo limefanikiwa!',
    pages: 'kurasa',
    published: 'Ilichapishwa',
    category: 'Kundi',
    author: 'Mwandishi',
    rating: 'Kiwango',
    reviews: 'maoni',
    addedToCart: 'Imeongezwa kwenye mkoba!',
    cartEmpty: 'Mkoba wako hauina kitu',
    continueReading: 'Endelea na safari yako ya kusoma',
    featuredBooks: 'Vitabu Maalum',
    newArrivals: 'Vitabu Vipya',
    bestsellers: 'Vitabu Vyenye Kuuzwa Zaidi',
    viewDetails: 'Ona Maelezo',
    quickView: 'Ona Haraka',
    wishlist: 'Ongeza kwenye Orodha ya Hamu',
    removeFromCart: 'Ondoa kutoka mkobani',
    proceedToCheckout: 'Endelea na Malipo',
    backToShopping: 'Rudi Ununuzi',
    orderTotal: 'Jumla ya Agizo',
    subtotal: 'Jumla Ndogo',
    shipping: 'Usafirishaji',
    free: 'Bure'
  }
};

export const sampleBooks = [
  {
    id: 1,
    title: "Executive Leadership Mastery",
    author: "Dr. Michael Richardson",
    category: "Leadership",
    price: 1500000,
    originalPrice: 2000000,
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=600&fit=crop",
    rating: 4.9,
    reviews: 324,
    pages: 12,
    publishedYear: 2024,
    inStock: true,
    stockCount: 15,
    description: "Transform your leadership style and drive exceptional business results through proven executive strategies.",
    featured: true,
    bestseller: false,
    newArrival: false
  },
  {
    id: 2,
    title: "Digital Business Transformation",
    author: "Sarah Chen",
    category: "Digital Strategy",
    price: 1200000,
    originalPrice: 1500000,
    image: "https://images.unsplash.com/photo-1532012197267-da84d127e765?w=400&h=600&fit=crop",
    rating: 4.8,
    reviews: 189,
    pages: 10,
    publishedYear: 2024,
    inStock: true,
    stockCount: 12,
    description: "Navigate the digital landscape and revolutionize your business model for sustainable growth.",
    featured: false,
    bestseller: true,
    newArrival: true
  },
  {
    id: 3,
    title: "Strategic Business Planning",
    author: "James Morrison",
    category: "Strategy",
    price: 980000,
    originalPrice: 1200000,
    image: "https://images.unsplash.com/photo-1509266272358-7701da638078?w=400&h=600&fit=crop",
    rating: 4.7,
    reviews: 256,
    pages: 14,
    publishedYear: 2023,
    inStock: true,
    stockCount: 20,
    description: "Master the art of strategic planning and create roadmaps that deliver exceptional business outcomes.",
    featured: true,
    bestseller: true,
    newArrival: false
  },
  {
    id: 4,
    title: "Peak Performance Coaching",
    author: "Dr. Amanda Foster",
    category: "Performance",
    price: 1800000,
    originalPrice: 2200000,
    image: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400&h=600&fit=crop",
    rating: 4.9,
    reviews: 403,
    pages: 16,
    publishedYear: 2024,
    inStock: true,
    stockCount: 8,
    description: "Unlock your full potential and achieve breakthrough performance in business and life.",
    featured: true,
    bestseller: false,
    newArrival: false
  },
  {
    id: 5,
    title: "Team Building & Culture",
    author: "Robert Williams",
    category: "Team Development",
    price: 1100000,
    originalPrice: 1400000,
    image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&h=600&fit=crop",
    rating: 4.6,
    reviews: 234,
    pages: 11,
    publishedYear: 2024,
    inStock: true,
    stockCount: 18,
    description: "Build high-performing teams and create winning organizational cultures that drive success.",
    featured: false,
    bestseller: true,
    newArrival: true
  },
  {
    id: 6,
    title: "Communication Excellence",
    author: "Lisa Rodriguez",
    category: "Communication",
    price: 850000,
    originalPrice: 1100000,
    image: "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=400&h=600&fit=crop",
    rating: 4.8,
    reviews: 367,
    pages: 8,
    publishedYear: 2023,
    inStock: true,
    stockCount: 25,
    description: "Master the art of persuasive communication and influence to accelerate your career growth.",
    featured: false,
    bestseller: false,
    newArrival: false
  },
  {
    id: 7,
    title: "Entrepreneurial Mindset",
    author: "David Thompson",
    category: "Entrepreneurship",
    price: 1350000,
    originalPrice: 1650000,
    image: "https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=400&h=600&fit=crop",
    rating: 4.7,
    reviews: 195,
    pages: 13,
    publishedYear: 2024,
    inStock: false,
    stockCount: 0,
    description: "Develop the entrepreneurial mindset needed to identify opportunities and create innovative solutions.",
    featured: false,
    bestseller: true,
    newArrival: true
  },
  {
    id: 8,
    title: "Sales & Negotiation Mastery",
    author: "Maria Santos",
    category: "Sales",
    price: 1050000,
    originalPrice: 1300000,
    image: "https://images.unsplash.com/photo-1556075798-4825dfaaf498?w=400&h=600&fit=crop",
    rating: 4.6,
    reviews: 312,
    pages: 9,
    publishedYear: 2023,
    inStock: true,
    stockCount: 14,
    description: "Master advanced sales techniques and negotiation strategies to close bigger deals consistently.",
    featured: false,
    bestseller: false,
    newArrival: false
  },
  {
    id: 9,
    title: "Change Management Excellence",
    author: "Dr. Andrew Lee",
    category: "Change Management",
    price: 1250000,
    originalPrice: 1550000,
    image: "https://images.unsplash.com/photo-1509266272358-7701da638078?w=400&h=600&fit=crop",
    rating: 4.5,
    reviews: 178,
    pages: 12,
    publishedYear: 2024,
    inStock: true,
    stockCount: 22,
    description: "Lead organizational change effectively and help teams embrace transformation with confidence.",
    featured: true,
    bestseller: false,
    newArrival: false
  },
  {
    id: 10,
    title: "Personal Branding & Influence",
    author: "Jennifer Parker",
    category: "Personal Development",
    price: 950000,
    originalPrice: 1200000,
    image: "https://images.unsplash.com/photo-1532012197267-da84d127e765?w=400&h=600&fit=crop",
    rating: 4.7,
    reviews: 243,
    pages: 10,
    publishedYear: 2024,
    inStock: true,
    stockCount: 16,
    description: "Build a powerful personal brand and expand your influence to accelerate career advancement.",
    featured: false,
    bestseller: true,
    newArrival: true
  }
];