// Mock useLanguage hook for demonstration

export const translations = {
  en: {
    shop: 'Book Shop',
    searchBooks: 'Search books...',
    addToCart: 'Add to Cart',
    orderNow: 'Order Now',
    price: 'Price',
    inStock: 'In Stock',
    outOfStock: 'Out of Stock',
    quantity: 'Quantity',
    filter: 'Filter',
    allCategories: 'All Categories',
    cart: 'Cart',
    total: 'Total',
    checkout: 'Checkout',
    orderSuccess: 'Order placed successfully!',
    pages: 'pages',
    published: 'Published',
    category: 'Category',
    author: 'Author',
    rating: 'Rating',
    reviews: 'reviews',
    addedToCart: 'Added to cart!',
    cartEmpty: 'Your cart is empty',
    continueReading: 'Continue your reading journey',
    featuredBooks: 'Featured Books',
    newArrivals: 'New Arrivals',
    bestsellers: 'Bestsellers',
    viewDetails: 'View Details',
    quickView: 'Quick View',
    wishlist: 'Add to Wishlist',
    removeFromCart: 'Remove from cart',
    proceedToCheckout: 'Proceed to Checkout',
    backToShopping: 'Back to Shopping',
    orderTotal: 'Order Total',
    subtotal: 'Subtotal',
    shipping: 'Shipping',
    free: 'Free'
  },
  sw: {
    shop: 'Duka la Vitabu',
    searchBooks: 'Tafuta vitabu...',
    addToCart: 'Ongeza kwenye Mkoba',
    orderNow: 'Agiza Sasa',
    price: 'Bei',
    inStock: 'Ipo Dukani',
    outOfStock: 'Haipatikani',
    quantity: 'Idadi',
    filter: 'Chuja',
    allCategories: 'Makundi Yote',
    cart: 'Mkoba',
    total: 'Jumla',
    checkout: 'Maliza Ununuzi',
    orderSuccess: 'Agizo limefanikiwa!',
    pages: 'kurasa',
    published: 'Ilichapishwa',
    category: 'Kundi',
    author: 'Mwandishi',
    rating: 'Kiwango',
    reviews: 'maoni',
    addedToCart: 'Imeongezwa kwenye mkoba!',
    cartEmpty: 'Mkoba wako hauina kitu',
    continueReading: 'Endelea na safari yako ya kusoma',
    featuredBooks: 'Vitabu Maalum',
    newArrivals: 'Vitabu Vipya',
    bestsellers: 'Vitabu Vyenye Kuuzwa Zaidi',
    viewDetails: 'Ona Maelezo',
    quickView: 'Ona Haraka',
    wishlist: 'Ongeza kwenye Orodha ya Hamu',
    removeFromCart: 'Ondoa kutoka mkobani',
    proceedToCheckout: 'Endelea na Malipo',
    backToShopping: 'Rudi Ununuzi',
    orderTotal: 'Jumla ya Agizo',
    subtotal: 'Jumla Ndogo',
    shipping: 'Usafirishaji',
    free: 'Bure'
  }
};

// Enhanced sample books data with Tanzanian context
export const sampleBooks = [
  {
    id: 1,
    title: "Mpenyo wa Kiuchumi",
    author: "James Mwangamba",
    category: "Uchumi",
    price: 35000,
    originalPrice: 45000,
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=600&fit=crop",
    rating: 4.8,
    reviews: 124,
    pages: 320,
    publishedYear: 2023,
    inStock: true,
    stockCount: 15,
    description: "Jinsi unavyoweza kufanikiwa kiuchumi wakati mgumu na mzuri wa kiuchumi.",
    featured: true,
    bestseller: false,
    newArrival: false
  },
  {
    id: 2,
    title: "Utandawazi wa Teknolojia Tanzania",
    author: "Dr. Amina Salum",
    category: "Teknolojia",
    price: 28000,
    originalPrice: 35000,
    image: "https://images.unsplash.com/photo-1532012197267-da84d127e765?w=400&h=600&fit=crop",
    rating: 4.6,
    reviews: 89,
    pages: 280,
    publishedYear: 2024,
    inStock: true,
    stockCount: 12,
    description: "Maendeleo ya teknolojia nchini Tanzania na fursa za biashara za kidijitali.",
    featured: false,
    bestseller: true,
    newArrival: true
  },
  {
    id: 3,
    title: "Mazao ya Kilimo Tanzania",
    author: "Eng. Godfrey Mwakipesile",
    category: "Kilimo",
    price: 22000,
    originalPrice: 28000,
    image: "https://images.unsplash.com/photo-1509266272358-7701da638078?w=400&h=600&fit=crop",
    rating: 4.7,
    reviews: 156,
    pages: 350,
    publishedYear: 2023,
    inStock: true,
    stockCount: 20,
    description: "Mbinu za kisasa za kilimo na mazao bora yanayoongoza uchumi wa Tanzania.",
    featured: true,
    bestseller: true,
    newArrival: false
  },
  {
    id: 4,
    title: "Historia ya Uhuru Tanzania",
    author: "Prof. Maria Nyerere",
    category: "Historia",
    price: 32000,
    originalPrice: 38000,
    image: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400&h=600&fit=crop",
    rating: 4.9,
    reviews: 203,
    pages: 420,
    publishedYear: 2022,
    inStock: true,
    stockCount: 8,
    description: "Hadithi kamili ya mapambano ya uhuru wa Tanzania na viongozi wake.",
    featured: true,
    bestseller: false,
    newArrival: false
  },
  {
    id: 5,
    title: "Uongozi wa Kijamii",
    author: "Mwalimu Hassan Kikwete",
    category: "Utawala",
    price: 26000,
    originalPrice: 32000,
    image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&h=600&fit=crop",
    rating: 4.5,
    reviews: 134,
    pages: 290,
    publishedYear: 2024,
    inStock: true,
    stockCount: 18,
    description: "Jinsi ya kuongoza jamii na taasisi kwa uwazi na uwongozi bora.",
    featured: false,
    bestseller: true,
    newArrival: true
  },
  {
    id: 6,
    title: "Fasihi ya Kiswahili",
    author: "Dkt. Euphrase Kezilahabi",
    category: "Fasihi",
    price: 18000,
    originalPrice: 24000,
    image: "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=400&h=600&fit=crop",
    rating: 4.8,
    reviews: 167,
    pages: 240,
    publishedYear: 2023,
    inStock: true,
    stockCount: 25,
    description: "Mkusanyiko wa riwaya, mashairi na hadithi za fasihi ya Kiswahili.",
    featured: false,
    bestseller: false,
    newArrival: false
  },
  {
    id: 7,
    title: "Utalii Tanzania: Rasilimali na Fursa",
    author: "Grace Mwalimu",
    category: "Utalii",
    price: 30000,
    originalPrice: 36000,
    image: "https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=400&h=600&fit=crop",
    rating: 4.7,
    reviews: 95,
    pages: 310,
    publishedYear: 2024,
    inStock: false,
    stockCount: 0,
    description: "Maeneo ya kitalii Tanzania na jinsi ya kuongeza kipato kutoka utalii.",
    featured: false,
    bestseller: true,
    newArrival: true
  },
  {
    id: 8,
    title: "Biashara za Ndogo Tanzania",
    author: "Rajab Mwalimu",
    category: "Biashara",
    price: 24000,
    originalPrice: 30000,
    image: "https://images.unsplash.com/photo-1556075798-4825dfaaf498?w=400&h=600&fit=crop",
    rating: 4.6,
    reviews: 112,
    pages: 265,
    publishedYear: 2023,
    inStock: true,
    stockCount: 14,
    description: "Mwongozo wa kuanzisha na kuendesha biashara ndogo nchini Tanzania.",
    featured: false,
    bestseller: false,
    newArrival: false
  },
  {
    id: 9,
    title: "Utamaduni wa Makabila Tanzania",
    author: "Mzee Selemani Kitenge",
    category: "Utamaduni",
    price: 20000,
    originalPrice: 25000,
    image: "https://images.unsplash.com/photo-1509266272358-7701da638078?w=400&h=600&fit=crop",
    rating: 4.4,
    reviews: 78,
    pages: 280,
    publishedYear: 2022,
    inStock: true,
    stockCount: 22,
    description: "Utamaduni, desturi na mila za makabila mbalimbali ya Tanzania.",
    featured: true,
    bestseller: false,
    newArrival: false
  },
  {
    id: 10,
    title: "Afya na Lishe Bora",
    author: "Dkt. Fatuma Mrisho",
    category: "Afya",
    price: 25000,
    originalPrice: 31000,
    image: "https://images.unsplash.com/photo-1532012197267-da84d127e765?w=400&h=600&fit=crop",
    rating: 4.5,
    reviews: 143,
    pages: 220,
    publishedYear: 2024,
    inStock: true,
    stockCount: 16,
    description: "Mwongozo wa lishe bora na jinsi ya kudumisha afya njema kwa familia.",
    featured: false,
    bestseller: true,
    newArrival: true
  }
];